sonar.projectKey=switch-monetique-service
sonar.projectName=switch-monetique-service
sonar.projectVersion=0.1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Genere par mvn test (plugin jacoco-maven-plugin deja configure dans pom.xml,
# seuil 80% lignes/branches verifie en phase verify)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8
